### ISSUE TITLE
Use Redis for scheduling

### ISSUE THREAD

**Issue by troysellers** [forcedotcom/OrgMonitor#2]
Is it possible to replace MongoDB with Redis as the store for the Job Queue? This will allow deployment of OrgMonitor to be completely contained within an Heroku Private Space (MongoDB attaches from outside a private space) and enable all regions for deploy targets.

**Comment by troysellers** [comment]
was trying to use this https://github.com/lykmapipo/kue-scheduler/issues/46 as a replacement for agenda.. but it requires a feature that Heroku Redis doesn't support unfortunately. Would require a different Heroku AddOn, thus defeating the purpose for replacing Mongo!

**Comment by AltiusRupert** [comment]
Hi ibigfoot, sorry to hijack this issue : 

I wondered if you could have a look at this other issue I have with OrgMonitor on Heroku and give me your point of view.
https://github.com/forcedotcom/OrgMonitor/issues/3

Thanks
